name: flutter_heyteacher_text_to_speech
description: "The flutter heyteacher text-to-speech (TTS) utilities localized in six languages"
version: 2.0.10+146
repository: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_text_to_speech
license: BSD 3-Clause
issue_tracker: https://codeberg.org/heyteacher/flutter_heyteacher_packages/issues
homepage: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_text_to_speech
documentation: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_text_to_speech
topics: [flutter, text-to-speech, tts]
funding: [https://liberapay.com/heyteacher]

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  flutter_heyteacher_locale: 
  flutter_heyteacher_platform: 
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.2.5
  intl: ^0.20.2
  logging: ^1.3.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_heyteacher_meta:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  generate: true
