name: flutter_heyteacher_meta
description: "A Flutter meta project implementing utilities for Flutter package and app project."
version: 2.2.1+260222212
repository: https://github.com/heyteacher/flutter_heyteacher_meta
license: BSD 3-Clause
issue_tracker: https://github.com/heyteacher/flutter_heyteacher_meta/issues
homepage: https://github.com/heyteacher/flutter_heyteacher_meta
documentation: https://github.com/heyteacher/flutter_heyteacher_meta
topics: [firebase,fastlane,firestore]
funding: [https://github.com/sponsors/heyteacher]

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  yaml_edit: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0