name: flutter_heyteacher_logger
description: "The flutter heyteacher package for logger utilities."
version: 2.0.5+136
repository: https://codeberg.org/heyteacher/flutter_heyteacher_logger
license: BSD 3-Clause
issue_tracker: https://codeberg.org/heyteacher/flutter_heyteacher_logger/issues
homepage: https://codeberg.org/heyteacher/flutter_heyteacher_logger
documentation: https://codeberg.org/heyteacher/flutter_heyteacher_logger
topics: [firebase,fastlane,firestore]
funding: [https://liberapay.com/heyteacher]

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  clock: ^1.1.2
  equatable: ^2.0.8
  firebase_analytics: ^12.1.3
  flutter:
    sdk: flutter
  flutter_heyteacher_auth: any
  flutter_heyteacher_locale: any
  flutter_heyteacher_platform: any
  flutter_heyteacher_views: any
  flutter_heyteacher_worker: any
  go_router: ^17.1.0
  json_annotation: ^4.11.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_heyteacher_meta: ^7.0.3+144
  flutter_test:
    sdk: flutter

flutter:
  generate: true