name: flutter_heyteacher_meta
description: "A Flutter meta project with utilities for Flutter packages and applications"
version: 2.0.0+260215111
#homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  yaml_edit: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0