# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

desc "fl _increment_flutter_build_number\n\tincrement flutter build number"
lane :_increment_flutter_build_number do
  Dir.chdir("../") do
    sh("dart run flutter_heyteacher_fastlane:version build")
  end
end

desc "fl build\n\tBuild flutter artifacts and rebuild pubspec.lock"
lane :build do
  Dir.chdir("../") do
    sh("rm pubspec.lock")
    sh("flutter pub upgrade")
  end
end

desc "fl buildweb [version:profile|debug]\n\tbuild web and run local webserver on it"
lane :buildweb do|options|
  test
  _increment_flutter_build_number
  _commit_pubspec
  version = ""
  if (options[:version] == "profile" || options[:version] == "debug")
      version = "--#{options[:version]}"
  end 
  Dir.chdir("../") do
    sh("flutter build web --no-wasm-dry-run #{version}")
    # open browser http://localhost:8080 and run local webserver
    sh("dart pub global run dhttpd --path build/web & open http://localhost:8080")
  end
end

desc "fl deployweb [version:profile|debug]\n\tdeploy web in firabase hosting"
lane :deployweb do|options|
  test
  _increment_flutter_build_number
  _commit_pubspec
  version = ""
  if (options[:version] == "profile" || options[:version] == "debug")
      version = "--#{options[:version]}"
  end
  Dir.chdir("../") do
    # build
    sh("flutter build web --no-wasm-dry-run #{version}")
    # deploy
    sh("firebase deploy --only hosting")
  end
end

desc "fl _commit_pubspec\n\tcommit pubspec.yaml"
lane :_commit_pubspec do
  tag = ""
  Dir.chdir("../") do
    tag = sh("dart run flutter_heyteacher_fastlane:version show")
  end
  # commit bump and push remote
  git_commit(path: "pubspec.yaml", message: "Version Bump #{tag}")
  push_to_git_remote
end


desc "fl docweb\n\trun local webserver on generated doc"
lane :docweb do
  Dir.chdir("../") do
    # open browser http://localhost:8080 and run local webserver
    sh("dart pub global run dhttpd --path doc/api & open http://localhost:8080")
  end
end

desc "fl doc\n\tgenerate doc and run webserver"
lane :doc do
  Dir.chdir("../") do
    # generate doc
    sh("dart doc")
    # run local webserver
    docweb
  end
end

desc "fl test\n\tRun tests"
lane :test do
  Dir.chdir("../") do
    sh("flutter test")
  end
end

desc "fl release version:mayor|minor|patch [suffix:<nmenonic_tag_suffix>]\n\trelease e version tagging in git"
lane :release do |options|
  _increment_flutter_build_number
   test
   tag = ""
   Dir.chdir("../") do
    tag = sh("dart run flutter_heyteacher_fastlane:version #{options[:version]}")
    # append tag suffix if founr
    if options[:suffix] != ""
      tag = "#{tag}_#{options[:suffix]}"
    end
  end
  # commit bump and push remote
  git_commit(path: "pubspec.yaml", message: "Version Bump #{tag}")
  push_to_git_remote
  # add tag and puth remote
  add_git_tag(tag: tag)
  push_git_tags(tag: tag)
end
