# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

desc "fl _increment_flutter_build_number\n\tincrement flutter build number"
lane :_increment_flutter_build_number do
  Dir.chdir("../") do
    sh("dart run flutter_heyteacher_fastlane:version build")
  end
end

desc "fl build\n\tBuild flutter artifacts and rebuild pubspec.lock"
lane :build do
  Dir.chdir("../") do
    sh("rm -rf pubspec.lock")
    sh("flutter pub upgrade")
  end
end

desc "fl docweb\n\trun local webserver on generated doc"
lane :docweb do
  Dir.chdir("../") do
    # open browser http://localhost:8080 and run local webserver
    sh("dart pub global run dhttpd --path doc/api & open http://localhost:8080")
  end
end

desc "fl doc\n\tgenerate doc and run webserver"
lane :doc do
  Dir.chdir("../") do
    # generate doc
    sh("dart doc")
    # run local webserver
    docweb
  end
end

desc "fl test\n\tRun tests"
lane :test do
  Dir.chdir("../") do
    sh("flutter test")
  end
end

desc "fl release version:mayor|minor|patch [suffix:<nmenonic_tag_suffix>] [create_release:true|false]\n\trelease e version tagging in git"
lane :release do |options|
  _increment_flutter_build_number
   test
   tag = ""
   Dir.chdir("../") do
    tag = sh("dart run flutter_heyteacher_fastlane:version #{options[:version]}")
    # append tag suffix if set
    if options[:suffix] != nil && options[:suffix] != ""
      tag = "#{tag}_#{options[:suffix]}"
    end
  end
  # commit bump and push remote
  sh("git branch tag")
  sh("git checkout tag")
  git_commit(path: "pubspec.yaml", message: "Version Bump #{tag}")
  sh("git checkout main")
  sh("git merge tag")
  sh("git branch tag -d")
  push_to_git_remote
  # add tag and puth remote
  puts "create tag #{tag}"
  add_git_tag(tag: tag)
  push_git_tags(tag: tag)
  # generate a release
  if options[:create_release] == true
    puts "create github release #{tag}"
    sh("gh release create #{tag} --generate-notes")
    puts "update CHANGELOG.md from releases"
    sh("git branch release")
    sh("git checkout release")
    Dir.chdir("../") do
      sh("changelog-from-release > CHANGELOG.md")
    end 
    git_commit(path: "CHANGELOG.md", message: "Update change log from release #{tag}")
    sh("git checkout main")
    sh("git merge release")
    sh("git branch release -d")
    push_to_git_remote
  end
end
