name: flutter_heyteacher_math
description: "The flutter heyteacher package for math utilities."
version: 2.0.1+128
homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_heyteacher_meta: ^6.0.0+134
  flutter_test:
    sdk: flutter

flutter:
