name: flutter_heyteacher_math
description: "The flutter heyteacher package for math utilities."
version: 2.0.3+132
repository: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_math
license: BSD 3-Clause
issue_tracker: https://codeberg.org/heyteacher/flutter_heyteacher_packages/issues
homepage: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_math
documentation: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_math
topics: [flutter, moving-average, moving-average-simple, moving-average-exponential, moving-average-weighted]
funding: [https://liberapay.com/heyteacher]

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_heyteacher_meta: ^7.2.1+156
  flutter_test:
    sdk: flutter

flutter:
