name: flutter_heyteacher_connectivity
description: "The flutter heyteacher package for connectivity utilities."
version: 2.0.2+130
publish_to: none
homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_heyteacher_views:
    path: ../flutter_heyteacher_views  
  logging: ^1.3.0

dev_dependencies:
  flutter_heyteacher_meta: ^6.0.0+134
  flutter_test:
    sdk: flutter

flutter:
  generate: true
