name: flutter_heyteacher_timer_workflow
description: "The flutter heyteacher package for manage timer workflow, that means tasks with an execution duration prefixed"
version: 2.0.5+136
repository: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_workflow
license: BSD 3-Clause
issue_tracker: https://codeberg.org/heyteacher/flutter_heyteacher_packages/issues
homepage: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_workflow
documentation: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_workflow
topics: [flutter, timer, workflow, timer-workflow]
funding: [https://liberapay.com/heyteacher]

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_heyteacher_locale: ^2.0.8+142 
  flutter_heyteacher_platform: ^2.0.5+136
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  fake_async: ^1.3.3
  flutter_heyteacher_meta: ^7.2.0+154
  flutter_test:
    sdk: flutter
  logging: ^1.3.0

flutter:
  generate: true
