name: flutter_heyteacher_locale
description: "The flutter heyteacher package for locale utilities."
version: 2.0.6+138
repository: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_locale
license: BSD 3-Clause
issue_tracker: https://codeberg.org/heyteacher/flutter_heyteacher_connectivity/issues
homepage: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_locale
documentation: https://codeberg.org/heyteacher/flutter_heyteacher_packages/src/branch/main/packages/flutter_heyteacher_locale
topics: [flutter, locale, localizations]
funding: [https://liberapay.com/heyteacher]

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  flutter_heyteacher_platform: any
  flutter_heyteacher_text_to_speech: any
  flutter_heyteacher_views: any
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_heyteacher_meta: ^7.0.3+144
  flutter_test:
    sdk: flutter
 
flutter:
  generate: true
  assets:
    - assets/locale/
