arb-dir: lib/src/l10n
template-arb-file: flutter_heyteacher_auth_en.arb
output-localization-file: flutter_heyteacher_auth.dart
output-class: FlutterHeyteacherAuthLocalizations
output-dir: lib/src/l10n
untranslated-messages-file: untranslated-messages.txt
