name: flutter_heyteacher_auth
description: "The flutter heyteacher package for authentication utilities."
version: 2.0.0+127
homepage:
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  clock: ^1.1.2
  firebase_auth: ^6.2.0
  firebase_remote_config: ^6.2.0
  firebase_ui_auth: ^3.0.1
  firebase_ui_oauth_google: ^2.0.1
  flutter:
    sdk: flutter
  flutter_heyteacher_firebase:
    path: ../flutter_heyteacher_firebase
  flutter_heyteacher_locale:
    path: ../flutter_heyteacher_locale
  flutter_heyteacher_platform:
    path: ../flutter_heyteacher_platform
  flutter_heyteacher_views:
    path: ../flutter_heyteacher_views
  go_router: ^17.1.0
  logging: ^1.3.0

dev_dependencies:
  flutter_heyteacher_meta: ^4.4.4+128
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
